name: 'PromptDrifter'
description: 'Run PromptDrifter CLI tests for LLM prompt configurations'
author: 'Code and Sorts'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  command:
    description: 'PromptDrifter command to run (init, run, validate, test-drift-type, migrate)'
    required: true
    default: 'run'
  files:
    description: 'Space-separated list of configuration files to process'
    required: false
  directory:
    description: 'Directory for init command'
    required: false
    default: '.'
  openai-api-key:
    description: 'OpenAI API key'
    required: false
  claude-api-key:
    description: 'Claude API key'
    required: false
  gemini-api-key:
    description: 'Gemini API key'
    required: false
  qwen-api-key:
    description: 'Qwen API key'
    required: false
  grok-api-key:
    description: 'Grok API key'
    required: false
  deepseek-api-key:
    description: 'DeepSeek API key'
    required: false
  mistral-api-key:
    description: 'Mistral API key'
    required: false
  no-cache:
    description: 'Disable caching'
    required: false
    default: 'false'
  cache-db:
    description: 'Path to cache database'
    required: false
  config-dir:
    description: 'Configuration directory path'
    required: false
  max-concurrent:
    description: 'Maximum concurrent requests'
    required: false
  drift-type:
    description: 'Drift type for test-drift-type command'
    required: false
  expected:
    description: 'Expected value for test-drift-type command'
    required: false
  actual:
    description: 'Actual value for test-drift-type command'
    required: false
  migrate-input:
    description: 'Input file for migrate command'
    required: false
  migrate-output:
    description: 'Output file for migrate command'
    required: false

outputs:
  result:
    description: 'Result of the PromptDrifter execution'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_COMMAND: ${{ inputs.command }}
    INPUT_FILES: ${{ inputs.files }}
    INPUT_DIRECTORY: ${{ inputs.directory }}
    INPUT_OPENAI_API_KEY: ${{ inputs.openai-api-key }}
    INPUT_CLAUDE_API_KEY: ${{ inputs.claude-api-key }}
    INPUT_GEMINI_API_KEY: ${{ inputs.gemini-api-key }}
    INPUT_QWEN_API_KEY: ${{ inputs.qwen-api-key }}
    INPUT_GROK_API_KEY: ${{ inputs.grok-api-key }}
    INPUT_DEEPSEEK_API_KEY: ${{ inputs.deepseek-api-key }}
    INPUT_MISTRAL_API_KEY: ${{ inputs.mistral-api-key }}
    INPUT_NO_CACHE: ${{ inputs.no-cache }}
    INPUT_CACHE_DB: ${{ inputs.cache-db }}
    INPUT_CONFIG_DIR: ${{ inputs.config-dir }}
    INPUT_MAX_CONCURRENT: ${{ inputs.max-concurrent }}
    INPUT_DRIFT_TYPE: ${{ inputs.drift-type }}
    INPUT_EXPECTED: ${{ inputs.expected }}
    INPUT_ACTUAL: ${{ inputs.actual }}
    INPUT_MIGRATE_INPUT: ${{ inputs.migrate-input }}
    INPUT_MIGRATE_OUTPUT: ${{ inputs.migrate-output }}
